### ISSUE TITLE
using boot/new instead of seancorfield/boot-new

### ISSUE THREAD

**Issue by enimiste** [mynomoto/hoplon-tutorial#1]
**Update the tutorial with :** 
`boot -d boot/new new -t hoplon -n hoplon-project`

**Instead of :** 
`boot -d seancorfield/boot-new new -t hoplon -n hoplon-project`

Source : [http://seancorfield.github.io/blog/2017/01/19/boot-new-moved/](Link)

**Comment by mynomoto** [comment]
Thanks for reporting!
